spring:
  data:
    mongodb:
      uri: "mongodb://admin:secret@localhost:3308/notifdb?authSource=admin"
  output.ansi.enabled: ALWAYS
  cloud:
    consul:
      discovery:
        healthCheckPath: /notif-health-check
        healthCheckInterval: 20s
      host: localhost
      port: 8500
      config:
        import: "optional:consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
        enabled: false