server:
  port: 8085

spring:
  application:
    name: notification-service  # Add this (must start with a letter)
  profiles:
    default: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"