server:
  port: 8080  # Port for the API Gateway

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  security:
    user:
      name: pfms
      password: pfms
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081   # URL for the user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=1

        - id: budget-service
          uri: http://localhost:8082   # URL for the budget-service
          predicates:
            - Path=/api/v1/budgets/**
          filters:
            - StripPrefix=1

        - id: expense-service
          uri: http://localhost:8083   # URL for the expense-service
          predicates:
            - Path=/api/v1/expenses/**
          filters:
            - StripPrefix=1

        - id: goal-service
          uri: http://localhost:8084   # URL for the goal-service
          predicates:
            - Path=/api/v1/goals/**
          filters:
            - StripPrefix=1

        - id: notification-service
          uri: http://localhost:8085   # URL for the notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=1

        - id: reporting-service
          uri: http://localhost:8086   # URL for the reporting-service
          predicates:
            - Path=/api/v1/reporting/**
          filters:
            - StripPrefix=1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always