services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq-message-broker
    ports:
      - "5672:5672"   # AMQP protocol port for apps to connect
      - "15672:15672" # Web Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_be_quiet true -rabbit loopback_users []
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
