spring.output.ansi.enabled=ALWAYS
spring.cloud.consul.discovery.health-check-path=/expense-health-check
spring.cloud.consul.discovery.health-check-interval=20s
spring.cloud.consul.host=localhost
spring.cloud.consul.port=8500
spring.cloud.consul.config.enabled=true
