server.port=8083
spring.application.name=expense-service
spring.datasource.url=jdbc:h2:mem:expensedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Consul
config.import="optional:consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
spring.cloud.consul.config.import-check.enabled=false

# Logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.delose.pfms=DEBUG

# Management
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
