spring.output.ansi.enabled=ALWAYS
spring.cloud.consul.discovery.health-check-path=/expense-health-check
spring.cloud.consul.discovery.health-check-interval=20s
spring.cloud.consul.discovery.hostname=expense-service
spring.cloud.consul.discovery.port=8083
spring.cloud.consul.discovery.preferIpAddress=true
spring.cloud.consul.host=http://host.docker.internal
spring.cloud.consul.port=8500
spring.cloud.consul.config.enabled=true
