#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://host.docker.internal:8761/eureka
#    register-with-eureka: true
#    fetch-registry: true

spring:
  output.ansi.enabled: ALWAYS
  cloud:
    consul:
      discovery:
        hostname: goal-service
        port: 8084
        healthCheckPath: /goal-health-check
        healthCheckInterval: 20s
        preferIpAddress: true
      host: http://host.docker.internal
      port: 8500
      config:
        enabled: true

# External Service Configuration
external:
  budget-service:
    url: http://host.docker.internal:8085
