services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pfms
      POSTGRES_USER: pfms
      POSTGRES_PASSWORD: pfms
    ports:
      - "5433:5433"

  service:
    build: .
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      SERVICE_NAME: transaction-service
      SERVICE_HOST: host.docker.internal
      CONSUL_HOST: host.docker.internal
      CONSUL_PORT: 8500
      DB_HOST: postgres
      DB_PORT: 5433
      DB_USER: pfms
      DB_PASS: pfms
      DB_NAME: pfms
    extra_hosts:
      - "host.docker.internal:host-gateway" # Mandatory for Linux contain
