server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: user-service
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    username: pfms
    password: pfms
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/myrealm
          jwk-set-uri: http://localhost:8080/auth/realms/myrealm/protocol/openid-connect/certs
jwt:
  secret: secret
  expiration: 3600