apiVersion: v2
name: pfms-chart
description: Umbrella chart for PFMS microservices
version: 0.1.0
type: application

dependencies:
  - name: account-service
    version: 0.1.0                # Must match version in account-service/Chart.yaml
    repository: "file://charts/account-service"
  - name: api-gateway
    version: 0.1.0                # Must match version in api-gateway/Chart.yaml
    repository: "file://charts/api-gateway"
