server:
  port: 8761

spring:
  application:
    name: discovery-server
  config:
    activate:
      on-profile: docker

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
