spring:
  kafka:
    bootstrap:
      servers: global-service-kafka:29092
  config:
    # This tells the service to fetch all other settings from the Config Server
    import: "optional:configserver:http://host.docker.internal:8888"
eureka:
  client:
    serviceUrl:
      defaultZone: http://host.docker.internal:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true