spring:
  application:
    name: budget-service
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
    consumer:
      group-id: budget-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  cache:
    caffeine:
      spec:
        maximumSize: 500
        expireAfterAccess: 600s

management:
  endpoints:
    web:
      exposure:
        include: metrics
  metrics:
    export:
      prometheus:
        enabled: true