services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pfms
      POSTGRES_USER: pfms
      POSTGRES_PASSWORD: pfms
    ports:
      - "5432:5432"

  service:
    build: .
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      RABBITMQ_URL: amqp://guest:guest@host.docker.internal:5672
      SERVICE_NAME: account-service
      SERVICE_HOST: host.docker.internal
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: pfms
      DB_PASS: pfms
      DB_NAME: pfms
    extra_hosts:
      - "host.docker.internal:host-gateway"